# Generated by Django 5.2.1 on 2025-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsection_alter_box_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='image',
        ),
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
