# Generated by Django 5.2.1 on 2025-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_box_image_alter_box_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogSection',
        ),
    ]
