# Generated by Django 5.2.1 on 2025-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_description_delete_blogsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='slug',
        ),
        migrations.AddField(
            model_name='box',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
