# Generated by Django 5.2.1 on 2025-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_box_images_boximage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boximage',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
